### ISSUE TITLE
Does it have the capability to learn.

### ISSUE THREAD

**Issue by EuphorianXD** [shasankp000/AI-Player#3]
Can It build on intelligence. And learn what its doing and slowly improve?

**Comment by shasankp000** [comment]
Yes the recent update has been focused on purely intelligence. However there is no "it" specific entity. The performance varies from language model to language model. Right now this mod performs the best with gemma2.

Which can of course remember past conversations, store conversations and whatever events happened in the world.

In the future update I am trying to build a "feedback loop" system where it can retrieve it's past actions and differ on what's right and what's wrong, and learn and build on that.


But yes so far you can have really intelligent conversations with the bot, or gemma2 in this case.

**Comment by shasankp000** [comment]
@EuphorianXD If you are interested in the technicalities of how it works, you can try reading the readme file!
