### ISSUE TITLE
Setup issue...

### ISSUE THREAD

**Issue by EuphorianXD** [shasankp000/AI-Player#7]
Ok so I don't really know how to set this up. I put ai-player1.0.2 in my mods, carpet mod, and fabric api. When I start, it says:

`Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
Replace 'OpenJDK 64-Bit Server VM' (java) 17 with version 21 or later.
More details:
Mod 'AI-Player' (ai-player) 1.0.2-hotfix-3 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!`

Can I get like a setup tutorial? I downloaded ollama and the 2 dependencies with ollama pull <pkg>

**Comment by shasankp000** [comment]
Yeah you need to install Java 21 and then configure the jvm settings in the launcher to that path.
This mod requires Java 21 for now, future updates it will be for the default java version

**Comment by EuphorianXD** [comment]
that's what i don't get... I have it. (I checked path, competing versions and everything)
`C:\Users\User>java --version
java 21.0.3 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)
`

**Comment by EuphorianXD** [comment]
Ok wait nvm. I had to set the specific javaw.exe in settings. you can close

**Comment by EuphorianXD** [comment]
hold on keep it open (sorry for all the problems) i got mc running... but the mod isn't active. the commands dont exist or anything

**Comment by shasankp000** [comment]
Could you send a log of what's going on?

**Comment by shasankp000** [comment]
Closing since no further response was provided
