### ISSUE TITLE
Language Model is not connecting

### ISSUE THREAD

**Issue by SaintFishy132014** [shasankp000/AI-Player#8]
Hey I was waiting for a bit for the bot to say something like "bot language model is connected" and it isn't working. https://prnt.sc/zabmqmbpfXmn

**Comment by AdyTech99** [comment]
Same here

**Comment by shasankp000** [comment]
Could you provide the logs? While this exact issue is happening?

**Comment by shasankp000** [comment]
Did you try setting the language model in the config manager by typing `/configMan` ?

**Comment by shasankp000** [comment]
Closed issue as it was left non-responsive
